package tictactoe;

import java.util.HashMap;

class PrecomputedMoves {
  public HashMap<String, Integer> states = new HashMap<String, Integer>();

  public  PrecomputedMoves() {
    states.put("X  XO OX ", 2);
    states.put(" O XOXXXO", 0);
    states.put("OX XXOXO ", 2);
    states.put("X OO X  X", 4);
    states.put("XXO O   X", 3);
    states.put("OO XX X  ", 2);
    states.put("OXOOXX  X", 6);
    states.put(" X  O   X", 0);
    states.put("O OXX X  ", 1);
    states.put("XOXOOXX  ", 7);
    states.put("OX XO   X", 2);
    states.put("  X OOX X", 3);
    states.put("XXOO XO X", 4);
    states.put("OXX OOX X", 3);
    states.put("OXO  XX  ", 4);
    states.put(" OX   OXX", 5);
    states.put("XOXXO O X", 7);
    states.put("XOXO  XXO", 4);
    states.put("XO OXXOX ", 8);
    states.put("OXXO X   ", 6);
    states.put(" O     XX", 6);
    states.put("  XXOOOXX", 0);
    states.put(" O X XOX ", 4);
    states.put("  X OX XO", 0);
    states.put("O   X   X", 2);
    states.put("XXOOOX X ", 6);
    states.put("  XOO  XX", 5);
    states.put(" OXXO X  ", 0);
    states.put("OO XXOXX ", 2);
    states.put("XOXXOX  O", 7);
    states.put("XOXOO  XX", 5);
    states.put("OX  OX X ", 2);
    states.put("XOX O   X", 5);
    states.put("  XXOX  O", 0);
    states.put("O  XOXOXX", 2);
    states.put("O  X  X  ", 1);
    states.put("X   O X  ", 3);
    states.put("  O  XX  ", 0);
    states.put("O OX   XX", 1);
    states.put("OX XO XOX", 2);
    states.put("XOX OOX X", 3);
    states.put("OX   XO X", 2);
    states.put("O X X    ", 6);
    states.put("X OOOXX X", 7);
    states.put("O OX XX  ", 1);
    states.put("OXO X X  ", 7);
    states.put("O  OXXX  ", 2);
    states.put("XOX OXOX ", 8);
    states.put("XO  OX X ", 6);
    states.put("OO XOXXX ", 2);
    states.put("OO X XX  ", 2);
    states.put("OX XOXOX ", 2);
    states.put("O XXXO   ", 6);
    states.put(" X  O XOX", 0);
    states.put("XO OOXX X", 7);
    states.put(" OXX XOXO", 4);
    states.put("OXXOO X X", 5);
    states.put(" XOOXXO X", 0);
    states.put("O XXOO XX", 6);
    states.put("OX  X    ", 7);
    states.put("XOXOOX X ", 8);
    states.put(" O X  OXX", 2);
    states.put(" OX    X ", 6);
    states.put("OXO  X X ", 4);
    states.put("XXO OX   ", 6);
    states.put("X  OO XX ", 5);
    states.put("OX XX  O ", 5);
    states.put("O XXO OXX", 5);
    states.put("OX  OXOXX", 2);
    states.put(" XX OOOXX", 3);
    states.put("OO  X XX ", 2);
    states.put("O O XX  X", 1);
    states.put("X XOO X  ", 1);
    states.put("O XXXOOX ", 1);
    states.put(" OX OXXXO", 0);
    states.put("    X    ", 0);
    states.put("O O X XX ", 1);
    states.put("OXXXOXO  ", 8);
    states.put("  X O OXX", 5);
    states.put(" OXX OOXX", 0);
    states.put("X        ", 4);
    states.put("X   O  X ", 3);
    states.put("XOX OX   ", 7);
    states.put("XXOO X   ", 4);
    states.put("OXO XX OX", 3);
    states.put("OXX O OXX", 3);
    states.put("  X OXX O", 0);
    states.put("XX OO XXO", 5);
    states.put(" X  O OXX", 0);
    states.put("OOXXXO  X", 6);
    states.put("OXOXO X X", 7);
    states.put("   XO XXO", 0);
    states.put("X  XO    ", 6);
    states.put("O  XXO  X", 1);
    states.put("O O  XXX ", 1);
    states.put("O XXOX   ", 8);
    states.put(" XXOOX XO", 0);
    states.put(" OOOXXXX ", 0);
    states.put("OXXOX    ", 6);
    states.put("O OXXOXX ", 1);
    states.put("O  X   X ", 2);
    states.put(" XOOXX   ", 7);
    states.put("  O  X X ", 0);
    states.put("  XOOX X ", 8);
    states.put("XOX OO XX", 3);
    states.put("O  XOX X ", 1);
    states.put("X OXOX   ", 6);
    states.put("X OOOX XX", 6);
    states.put("OX  X XO ", 2);
    states.put("X OOXX XO", 1);
    states.put(" XX OX  O", 0);
    states.put("O OX X X ", 1);
    states.put("O X XXO  ", 3);
    states.put("  OOXX  X", 0);
    states.put(" O   X X ", 6);
    states.put("OX XXO   ", 7);
    states.put("XO XOX   ", 6);
    states.put("OXX OX   ", 8);
    states.put("X X OO  X", 1);
    states.put("XO XXOOX ", 8);
    states.put("  XOOXXXO", 0);
    states.put("  XXOO  X", 0);
    states.put("OX   X   ", 6);
    states.put("XO  OXX  ", 7);
    states.put(" O   XOXX", 2);
    states.put(" O OXXOXX", 0);
    states.put("XOOXOX  X", 6);
    states.put("OXOXXOX  ", 8);
    states.put("O  XOXXOX", 1);
    states.put("OXOX   X ", 4);
    states.put("OO XX XXO", 2);
    states.put("OX XO OXX", 2);
    states.put("O X X OX ", 3);
    states.put(" XOOXX OX", 0);
    states.put("    OXXOX", 1);
    states.put("XX OO  X ", 2);
    states.put("OXO  XOXX", 3);
    states.put("OOX  XXXO", 4);
    states.put(" XOOOXXX ", 8);
    states.put("OX OXX OX", 6);
    states.put(" O  X XXO", 2);
    states.put("X O  X   ", 3);
    states.put("XO  O  XX", 6);
    states.put("OOX X  X ", 6);
    states.put("  X OX   ", 8);
    states.put("OXXXOO  X", 6);
    states.put("X XOO  X ", 5);
    states.put("XO    XXO", 3);
    states.put("X   O XXO", 3);
    states.put("XOXXO    ", 7);
    states.put("OXOXOXX  ", 8);
    states.put("OO OXXXX ", 2);
    states.put("OXXOOX X ", 6);
    states.put(" OOXX OXX", 0);
    states.put("OXXOXX O ", 6);
    states.put(" XX OO  X", 3);
    states.put("OXOXX XO ", 5);
    states.put("XX XO O  ", 2);
    states.put(" OXOXXOX ", 0);
    states.put("O OOXXXX ", 1);
    states.put("OO  XXOXX", 2);
    states.put("O  XX    ", 5);
    states.put("  O XX   ", 3);
    states.put("O  XO XX ", 8);
    states.put("    OX  X", 2);
    states.put("OXOXO  XX", 6);
    states.put("XO OX XXO", 2);
    states.put("XOOX  OXX", 4);
    states.put(" O  OXXX ", 8);
    states.put("XXOOO X X", 5);
    states.put("OX  XXO  ", 3);
    states.put(" O X   X ", 6);
    states.put("O  XOX  X", 2);
    states.put("XO XO OXX", 2);
    states.put("XOX O XXO", 3);
    states.put("OX X XO  ", 4);
    states.put("XX  O    ", 2);
    states.put("X OO X X ", 4);
    states.put("O OXOXXX ", 1);
    states.put("OXO XXO X", 3);
    states.put("  OOXX X ", 1);
    states.put("  X OO XX", 3);
    states.put("OX XO  X ", 2);
    states.put("O XXX O  ", 5);
    states.put("O XOXX   ", 6);
    states.put("XO X  OX ", 4);
    states.put("XOXXO OX ", 5);
    states.put("OX  O XX ", 8);
    states.put("OXX O   X", 5);
    states.put(" OO XXXXO", 0);
    states.put("    OXOXX", 2);
    states.put("O O  XX X", 1);
    states.put("XXOOOXX  ", 7);
    states.put("XO XO   X", 6);
    states.put("XO  O X X", 7);
    states.put(" OX XOOXX", 0);
    states.put(" O XX OX ", 5);
    states.put("OXX OO XX", 3);
    states.put("OX  OX  X", 2);
    states.put("    O XX ", 8);
    states.put("OXX O XOX", 5);
    states.put(" XOO X  X", 6);
    states.put("O  XXO X ", 1);
    states.put(" XOXOX   ", 0);
    states.put("OOXXO XX ", 8);
    states.put("        X", 4);
    states.put("   XO X  ", 0);
    states.put("OX   XOX ", 3);
    states.put("O   X  X ", 1);
    states.put("OX  OXXOX", 2);
    states.put("XO XOXOX ", 2);
    states.put(" OX O XX ", 8);
    states.put("XOX  OOXX", 4);
    states.put("O XXO   X", 5);
    states.put("OXXOO  XX", 5);
    states.put("O XXOOX X", 7);
    states.put("OXO OXXX ", 8);
    states.put("OXXXX OO ", 8);
    states.put("XX OO X  ", 5);
    states.put("OXXOOXX  ", 8);
    states.put("X X OX  O", 1);
    states.put("OXX X O  ", 3);
    states.put("XXOOO  XX", 5);
    states.put("  X O   X", 5);
    states.put("O XXO XOX", 1);
    states.put("  OXOXX  ", 0);
    states.put("O O XX X ", 1);
    states.put("OXXO  X  ", 4);
    states.put("  X O XOX", 1);
    states.put("OX      X", 4);
    states.put("OO  XX X ", 2);
    states.put("X X OOOXX", 3);
    states.put(" O XOXX  ", 0);
    states.put("OXXXXOO  ", 7);
    states.put(" OX  XOX ", 8);
    states.put("X OOXX   ", 8);
    states.put("XOX  XOXO", 3);
    states.put("OXXO   X ", 4);
    states.put("OX XXO OX", 2);
    states.put("XO  OXXXO", 3);
    states.put("XXO O X  ", 3);
    states.put(" O XXOOXX", 0);
    states.put("X  OOX X ", 2);
    states.put("X OO XX  ", 4);
    states.put("OXOOXXX  ", 7);
    states.put("X XOOX XO", 1);
    states.put(" X  O X  ", 0);
    states.put("O OXOXX X", 1);
    states.put("OXXOXO  X", 6);
    states.put("OOXXOX X ", 8);
    states.put("O OXX   X", 1);
    states.put(" O  OXX X", 7);
    states.put("XO   XOX ", 4);
    states.put("  X      ", 4);
    states.put("OXO  X  X", 6);
    states.put("OX  XX O ", 3);
    states.put("X  XOXO  ", 1);
    states.put("OX XO X  ", 8);
    states.put(" O  XXOX ", 3);
    states.put("OXX XXOO ", 3);
    states.put("O XX     ", 4);
    states.put("  O OXX X", 7);
    states.put("O   X X  ", 2);
    states.put("XOO OXX X", 7);
    states.put("OXOXOX X ", 6);
    states.put("  XOO XX ", 5);
    states.put("OO XXO XX", 2);
    states.put("XXOOXX O ", 8);
    states.put("XOXOO XX ", 5);
    states.put("X   OX   ", 1);
    states.put("OXO OXX X", 7);
    states.put("XOX O X  ", 3);
    states.put("O  X    X", 2);
    states.put("X   O   X", 1);
    states.put("  O  X  X", 0);
    states.put("OXO X XOX", 3);
    states.put("O OX  XX ", 1);
    states.put(" O    XX ", 8);
    states.put("OOXXXO X ", 6);
    states.put("OO X  XX ", 2);
    states.put("OXX      ", 3);
    states.put("OOX X OXX", 3);
    states.put("    OXXXO", 0);
    states.put("X   O XOX", 1);
    states.put("O OX X  X", 1);
    states.put("O  OXX  X", 2);
    states.put("OXO X   X", 7);
    states.put(" OXXOXOX ", 8);
    states.put(" OX XXOXO", 3);
    states.put("O OXXOX X", 1);
    states.put("OO XOX XX", 2);
    states.put("XO XX OXO", 5);
    states.put("  OXOX X ", 0);
    states.put("XOO OX XX", 6);
    states.put(" XOO XOXX", 0);
    states.put("OO X XXXO", 2);
    states.put("X  OO  XX", 5);
    states.put("OXOX XO X", 4);
    states.put("O O XXX  ", 1);
    states.put("OO  X  XX", 2);
    states.put("OXXXXO O ", 6);
    states.put("O O X  XX", 1);
    states.put("OO XXOX X", 2);
    states.put(" XOOOXX X", 7);
    states.put(" O XOXOXX", 2);
    states.put("OXO XXXO ", 3);
    states.put(" O X  XXO", 0);
    states.put("O  XXOX  ", 2);
    states.put("O O  X XX", 1);
    states.put("XOX O  X ", 3);
    states.put(" OOX XOXX", 0);
    states.put("OOXX  XXO", 4);
    states.put(" OOOXX XX", 0);
    states.put(" OX   XXO", 4);
    states.put("X OOOXXX ", 8);
    states.put("  OOXXX  ", 0);
    states.put("     X   ", 2);
    states.put("XO OOXXX ", 8);
    states.put("  X O XXO", 0);
    states.put("X X O    ", 1);
    states.put(" OXXO OXX", 5);
    states.put("OOX XXOX ", 3);
    states.put("XO  X OX ", 8);
    states.put("OX  X  OX", 2);
    states.put("X  OOXX  ", 1);
    states.put("O  X X   ", 4);
    states.put("O OOXXX X", 1);
    states.put("OXXO OX X", 4);
    states.put("X   O OXX", 2);
    states.put("X  OO X X", 5);
    states.put("  OXOXXOX", 1);
    states.put("OX XOXO X", 2);
    states.put(" X  O XXO", 0);
    states.put(" OOXX XXO", 0);
    states.put("   XO OXX", 2);
    states.put(" OX X OX ", 0);
    states.put("XXOXO    ", 6);
    states.put("X O OXXOX", 1);
    states.put("OOXXO X X", 7);
    states.put("XOO X XXO", 5);
    states.put("       X ", 1);
    states.put("O XXXOO X", 1);
    states.put("OXX X  O ", 6);
    states.put("  X O  X ", 3);
    states.put("X XXO O  ", 1);
    states.put(" XO  X   ", 3);
    states.put("XOX OXX O", 7);
    states.put("XO  OX  X", 2);
    states.put(" XOOXXXO ", 0);
    states.put("X O OX  X", 1);
    states.put(" XOO X X ", 4);
    states.put("XO     X ", 6);
    states.put("OO X  X X", 2);
    states.put("OX OXXXO ", 2);
    states.put(" OXXO XXO", 0);
    states.put(" XOOOX XX", 6);
    states.put("XOX   OX ", 4);
    states.put("O O X X X", 1);
    states.put("O OX  X X", 1);
    states.put("O XXO  X ", 8);
    states.put("OO OXX XX", 2);
    states.put("    O X X", 7);
    states.put("OXOXOX  X", 6);
    states.put(" O  X  X ", 0);
    states.put("  OX X   ", 4);
    states.put("OXOXX  OX", 5);
    states.put(" O   XXXO", 0);
    states.put("OX OXX   ", 6);
    states.put("X OOXXX O", 1);
    states.put("    OXX  ", 1);
    states.put("XO XOXO X", 2);
    states.put("OXOXO XX ", 8);
    states.put("O  XO  XX", 6);
    states.put("  O OX XX", 6);
    states.put(" OX O X X", 7);
    states.put(" OXX  OX ", 4);
    states.put("OX     X ", 4);
    states.put("OX  O X X", 7);
    states.put("O OXX  X ", 1);
    states.put("OXX O  X ", 3);
    states.put("XOXXOO  X", 7);
    states.put("X  XO O X", 1);
    states.put("O OOXX XX", 1);
    states.put(" XO OXXOX", 0);
    states.put("XXO O  X ", 3);
    states.put("OO XX  X ", 2);
    states.put("O  XOXX  ", 1);
    states.put("OOXXX OX ", 5);
    states.put("XO    OXX", 4);
    states.put("O OXOX XX", 1);
    states.put("OOXXOXX  ", 7);
    states.put("OXOX    X", 4);
    states.put("O X X O X", 3);
    states.put("XOXOO X X", 5);
    states.put("OO  XXXXO", 2);
    states.put("OXXO O XX", 4);
    states.put("O  OXX X ", 1);
    states.put("OX X     ", 4);
    states.put("OX  O  XX", 6);
    states.put("X XOO XXO", 5);
    states.put("OXX O X  ", 3);
    states.put(" XXOO  X ", 0);
    states.put(" XO OX  X", 6);
    states.put("   X     ", 0);
    states.put("XXOOOX  X", 6);
    states.put("  XXO    ", 0);
    states.put("XXOOXX  O", 7);
    states.put(" OXXXOOX ", 0);
    states.put("O  XO X X", 7);
    states.put("XOX OX XO", 3);
    states.put("OX  OXX  ", 8);
    states.put("OX XOX   ", 2);
    states.put("      X  ", 4);
    states.put("    O  XX", 6);
    states.put("XOX O OXX", 5);
    states.put(" OX OXX  ", 7);
    states.put(" XOO XX  ", 4);
    states.put("XOX X OXO", 3);
    states.put("   XO XOX", 1);
    states.put("OXX  XO  ", 3);
    states.put(" X       ", 0);
    states.put("   XO   X", 0);
    states.put("OOXX  X  ", 4);
    states.put("XO  OXOXX", 2);
    states.put("XO  XXOXO", 3);
    states.put("OXXOO XX ", 5);
    states.put("O XXO X  ", 1);
    states.put(" XX O    ", 0);
    states.put("OXO OX XX", 6);
    states.put("OO XX OXX", 2);
    states.put(" OO XXOXX", 0);
    states.put("XXOOO XX ", 5);
    states.put("OO XOXX X", 2);
    states.put("  X O X  ", 1);
    states.put("O   XX   ", 3);
    states.put("X  OOXXXO", 1);
    states.put("  OXOX  X", 0);
    states.put(" O  X OXX", 0);
    states.put("XOOOXX X ", 8);
    states.put("OXXO    X", 5);
    states.put("OXX X OOX", 3);
    states.put("XO O XXXO", 2);
    states.put("OX    X  ", 4);
    states.put("XOO  XOXX", 4);
    states.put("OXXXO    ", 8);
    states.put("XOXXOXO  ", 7);
    states.put("OOXOXX X ", 6);
  }
}
